package com.yuanshi.iotpro.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yuanshi.iotpro.publiclib.bean.FriendsApplyBean;
import com.yuanshi.iotpro.publiclib.bean.LoginInfoBean;
import com.yuanshi.iotpro.publiclib.bean.UserInfoBean;

import com.yuanshi.iotpro.dao.FriendsApplyBeanDao;
import com.yuanshi.iotpro.dao.LoginInfoBeanDao;
import com.yuanshi.iotpro.dao.UserInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsApplyBeanDaoConfig;
    private final DaoConfig loginInfoBeanDaoConfig;
    private final DaoConfig userInfoBeanDaoConfig;

    private final FriendsApplyBeanDao friendsApplyBeanDao;
    private final LoginInfoBeanDao loginInfoBeanDao;
    private final UserInfoBeanDao userInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsApplyBeanDaoConfig = daoConfigMap.get(FriendsApplyBeanDao.class).clone();
        friendsApplyBeanDaoConfig.initIdentityScope(type);

        loginInfoBeanDaoConfig = daoConfigMap.get(LoginInfoBeanDao.class).clone();
        loginInfoBeanDaoConfig.initIdentityScope(type);

        userInfoBeanDaoConfig = daoConfigMap.get(UserInfoBeanDao.class).clone();
        userInfoBeanDaoConfig.initIdentityScope(type);

        friendsApplyBeanDao = new FriendsApplyBeanDao(friendsApplyBeanDaoConfig, this);
        loginInfoBeanDao = new LoginInfoBeanDao(loginInfoBeanDaoConfig, this);
        userInfoBeanDao = new UserInfoBeanDao(userInfoBeanDaoConfig, this);

        registerDao(FriendsApplyBean.class, friendsApplyBeanDao);
        registerDao(LoginInfoBean.class, loginInfoBeanDao);
        registerDao(UserInfoBean.class, userInfoBeanDao);
    }
    
    public void clear() {
        friendsApplyBeanDaoConfig.clearIdentityScope();
        loginInfoBeanDaoConfig.clearIdentityScope();
        userInfoBeanDaoConfig.clearIdentityScope();
    }

    public FriendsApplyBeanDao getFriendsApplyBeanDao() {
        return friendsApplyBeanDao;
    }

    public LoginInfoBeanDao getLoginInfoBeanDao() {
        return loginInfoBeanDao;
    }

    public UserInfoBeanDao getUserInfoBeanDao() {
        return userInfoBeanDao;
    }

}
